version: "3.8"

services:
  fastapi_app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app1
    ports:
      - "8001:8000"
    restart: always

  fastapi_app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app2
    ports:
      - "8002:8000"
    restart: always

  fastapi_app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app3
    ports:
      - "8003:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
    depends_on:
      - fastapi_app1
      - fastapi_app2
      - fastapi_app3
